// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var $$Date = require("../src/Date.js");

var d = $$Date.now(/* () */0);

console.log($$Date.toJson(d));

var d2 = $$Date.addMonth(10, d);

console.log($$Date.toJson(d2));

exports.d = d;
exports.d2 = d2;
/* d Not a pure module */
